name: Run CI
on:
  push:
    paths:
      - /lib/**
      - /test/**
      - /pubspec.yaml
      - /.github/workflows/run_ci.yml
      - /example/lib/**
      - /example/test/**
      - /example/pubspec.yaml
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        flutter: [stable, beta]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
      - run: flutter --version
      # Install dev_test binaries
      - run: flutter pub global activate dev_test
      # Run common validation test (analyzer, format, test) on your package (and nested packages)
      - run: flutter pub global run dev_test:run_ci
